
CREATE TABLE ITEM_REQUESTS (id INT PRIMARY KEY,
  email VARCHAR(128) NOT NULL,
  keyword VARCHAR(256) NOT NULL,
  categories VARCHAR(512) NOT NULL,
  status INT NOT NULL,
  createDate DATETIME DEFAULT CURRENT_DATE
)

